### ISSUE TITLE
Unable to parse Extensions in GPX

### ISSUE THREAD

**Issue by prasad456** [ticofab/android-gpx-parser#11]
How can I parse Extensions which are in GPX file.

**Comment by ticofab** [comment]
Thanks for opening. Can you please show an example of the GPX file that gives you trouble?

**Comment by prasad456** [comment]
I had changed ".gpx" to txt to upload here. Please check this
[sample.txt](https://github.com/ticofab/android-gpx-parser/files/1054065/sample.txt)

**Comment by prasad456** [comment]
Hi Ticofab,

Have you check the sample text, which uploaded in previous. Please let me know any issues.

**Comment by ticofab** [comment]
Hey @prasad456, it seems like your XML is not part of the GPX standard. I suggest that you use my library to parse the GPX-compliant part of your XML and then parse the rest yourself.
