### ISSUE TITLE
Problem with JodaTime

### ISSUE THREAD

**Issue by Barthomeus** [ticofab/android-gpx-parser#13]
Hi, I'm getting  java.lang.NoClassDefFoundError: org.joda.time.format.ISODateTimeFormat. I have Joda dependencie added to my build.gradle and  annotation multiDexEnabled true but its not working :/

**Comment by ticofab** [comment]
Closing as no further response.

**Comment by abhiank** [comment]
@ticofab I'm having this issue in the latest version. I checked my app dependency tree and `io.ticofab.androidgpxparser:parser` did not have joda time as a sub-dependency. 

<img width="500" alt="Screen Shot 2019-09-15 at 6 48 01 PM" src="https://user-images.githubusercontent.com/8065733/64922140-68f8d300-d7e9-11e9-94b9-0bb356aaa965.png">

It failed when I tried to parse this GPX file - 
[2019-09-14_93505490_newtestroute_kumoot.gpx.zip](https://github.com/ticofab/android-gpx-parser/files/3613785/2019-09-14_93505490_newtestroute_kumoot.gpx.zip)

On including the latest Joda time dependency into my build.gradle, this issue does not happen anymore.

**Comment by ticofab** [comment]
hey @abhiank , thanks for commenting and the investigation! I am not sure where this issue come from, I think your build system should fix it, but I will look into this. I have just released 1.6.0 . This issue doesn't seem to be a problem for many people so I think I'll deal with this in the next wave of work I spend on this :)

**Comment by abhiank** [comment]
I tried looking more into the issue but my experience with building libraries is a little limited. Found a couple questions which mentioned that dependencies needed to be explicitly added/copied to the library aar. But the code I tried didn't work. Not sure if its my build system which is the problem source either. 

> I have just released 1.6.0

Ah cool. I'll try 1.6.0. A question - why have you mentioned "api" as the way to mention the dependency in gradle? Shouldn't it be "implementation"?

> I will likely drop JodaTime soon and just use java.time which is available from API 26 onwards.

I see. But JodaTime will continue to be used for API <26 ?

**Comment by ticofab** [comment]
About dropping JodaTime, users that want to distribute their app to < 26 will have to use an older version of the library. About `api`, the difference is in the way things are linked. [This article](https://medium.com/mindorks/implementation-vs-api-in-gradle-3-0-494c817a6fa) explains it quite briefly.
