### ISSUE TITLE
Switch to java.time instead of Joda Datetime

### ISSUE THREAD

**Issue by ticofab** [ticofab/android-gpx-parser#16]
It is about time we use the native Java implementation for date & time.

**Comment by frogboiled** [comment]
The library (1.1.2) still not parse the `<desc>` (description) field from waypoint!
Can you please add it in the next version?
thanks in advance.

`// part from real gpx file.
<wpt lat="48.859730" lon=" 2.351660">
    <time>2015-09-14T06:54:35Z</time>
    <name>-=1=-</name>
    <ele>150</ele>
   <desc>A text description of the element. Holds additional information about the element intended for the user, not the GPS.</desc>
</wpt>`

**Comment by ticofab** [comment]
Hey @frogboiled , can you please open a separate issue for this? That makes it easier to track :)

**Comment by ticofab** [comment]
Closing this issue - as long as we stay with API < 26, java.time (specifically the ISO_INSTANT formatter that we need) is not supported.

**Comment by ticofab** [comment]
@frogboiled , the desc field is parsed in version 1.2.0 !
