### ISSUE TITLE
Parse waypoint description

### ISSUE THREAD

**Issue by ticofab** [ticofab/android-gpx-parser#17]
The library (1.1.2) still not parse the <desc> (description) field from waypoint!
Can you please add it in the next version?
thanks in advance.

// part from real gpx file. <wpt lat="48.859730" lon=" 2.351660"> <time>2015-09-14T06:54:35Z</time> <name>-=1=-</name> <ele>150</ele> <desc>A text description of the element. Holds additional information about the element intended for the user, not the GPS.</desc> </wpt>

**Comment by ticofab** [comment]
Fixed in 1.2.0 .

**Comment by frogboiled** [comment]
@ticofab 
Thanks a lot!
The best android gpx parser!!!
