### ISSUE TITLE
I need to first download 

### ISSUE THREAD

**Issue by goksenin** [ticofab/android-gpx-parser#18]
Hi, 

I am making http get request to download gpx file from server (i need to download it. it is a requirement)

private void callAPI(String routeId) {

        NetworkBuilder.getAppNetwork().getRoute(routeId).enqueue(new Callback<ResponseBody>() {
            @Override
            public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {

                Log.e("@@@@@@@@@@@", "API SUCCESS");
                try {
                    File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
                    File file = new File(path, "cyclingRoute.gpx");
                    FileOutputStream fileOutputStream = new FileOutputStream(file);
                    IOUtils.write(response.body().bytes(), fileOutputStream);
                    parseRoute(file);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

            @Override
            public void onFailure(Call<ResponseBody> call, Throwable t) {
                
                Log.e("@@@@@@@@@@@", "API FAILS" + t.getMessage());
            }
        });
    }

with parseRoute function i am trying to parse gpx but input stream "is" throws a null pointer exception.
I also tried implementing 

InputStream in = getAssets().open("cyclingRoute.gpx"); but it said no file or directory found.

private void parseRoute(File file){

        GPXParser mParser = new GPXParser();
        Gpx parsedGpx = null;
        try {
            InputStream  is= getClass().getResourceAsStream(file.getName());
            parsedGpx = mParser.parse(is);
        } catch (IOException | XmlPullParserException e) {
            // do something with this exception
            e.printStackTrace();
        }
        if (parsedGpx == null) {
            // error parsing track
        } else {
            // do something with the parsed track
            List<Track> tracks = parsedGpx.getTracks();
            for (int i = 0; i < tracks.size(); i++) {
                Track track = tracks.get(i);
                Log.d(TAG, "track " + i + ":");
                List<TrackSegment> segments = track.getTrackSegments();
                for (int j = 0; j < segments.size(); j++) {
                    TrackSegment segment = segments.get(j);
                    Log.d(TAG, "  segment " + j + ":");
                    for (TrackPoint trackPoint : segment.getTrackPoints()) {
                        Log.d(TAG, "    point: lat " + trackPoint.getLatitude() + ", lon " + trackPoint.getLongitude());
                    }
                }
            }
        }
    }

any help will be appriciated!!!

**Comment by ticofab** [comment]
Hey @goksenin , it looks like this issue is utterly unrelated to this library. I guess there is something wrong in how you download or save the gpx file, try asking for help on StackOverflow :)

**Comment by goksenin** [comment]
Hey @ticofab !

I changed my code where i write my file on external directory and read from them. Although i can write it to internal directory, i cant read it from getAssets().open("test.gpx"); because i cant download my file to assets folder. Is there any way to read my file either from internal or external directory?
