### ISSUE TITLE
Error:No service of type Factory<LoggingManagerInternal> available in ProjectScopeServices.

### ISSUE THREAD

**Issue by ashishsharma30** [ticofab/android-gpx-parser#2]
Solution:

dependencies {
    classpath 'com.android.tools.build:gradle:2.2.2'
    classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
}

**Comment by StuStirling** [comment]
Fixed in #4

**Comment by ticofab** [comment]
Released in 0.1.6
