### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by ryust** [ticofab/android-gpx-parser#23]
The attached file fails during parsing although it can be read by other GPX track programs. Any suggestions on how to properly parse the file?

[Shores of Derwentwater.txt](https://github.com/ticofab/android-gpx-parser/files/3397414/Shores.of.Derwentwater.txt)

**Comment by ticofab** [comment]
Hey @ryust thanks for opening this issue. Is it still happening?
I will spend some time with it to reproduce it / fix it as soon as I can.

**Comment by ryust** [comment]
Yes, it always happens. I just made a copy of the parser and commented out the code for TAG_EXTENSIONS since that is where it was failing to get past the issue.

**Comment by ticofab** [comment]
Fixed in 1.6.0
