### ISSUE TITLE
Migrate to Kotlin

### ISSUE THREAD

**Issue by ticofab** [ticofab/android-gpx-parser#24]

**Comment by msbit** [comment]
With this guy, how did you see this going?

I've put together https://github.com/msbit/android-gpx-parser/tree/kotlin, which is pretty much a straight conversion (with a bunch of Kotlin idioms thrown in). The only contentious bit would be the changes made as part of https://github.com/msbit/android-gpx-parser/tree/pre-kotlin, basically adding getters to the nested `Builder`s so the same pattern could ~translate to Kotlin.

**Comment by msbit** [comment]
Actually, I'll put together a PR and we can go over that there :)

**Comment by ticofab** [comment]
I came to the conclusion that as long as Android & Kotlin guarantee full Java support and interoperability, it is wiser not to change everything only for the sake of it and the operation only poses risks and no concrete advantages. Thanks for the energy you put in this @msbit , I truly appreciate it and I hope you will understand my reasoning.
