### ISSUE TITLE
Move to maven central 

### ISSUE THREAD

**Issue by herberlin** [ticofab/android-gpx-parser#36]
As you probably know the JCenter repository is deprecated and readonly since march 31st. http://developer.android.com/r/tools/jcenter-end-of-service

Threrefor it would be nice if you could move your library to another maven repository, e.g. maven central.

Thanks and greetings

Achim

**Comment by ticofab** [comment]
Hey @herberlin - the project is already moved to Jitpack, see README :)
If you are using this library, feel free to add your project (with link) in the README with a PR.
