### ISSUE TITLE
Cannot access time

### ISSUE THREAD

**Issue by moopat** [ticofab/android-gpx-parser#37]
I cannot access `point.time` because of the following error:

> Cannot access class 'org.joda.time.DateTime'. Check your module classpath for missing or conflicting dependencies

I am pretty sure that this is because 

`implementation 'net.danlew:android.joda:2.10.9.1'`

(from the library's `build.gradle`) does not expose `org.joda.time` classes to apps integrating your library. Changing it to 

`api 'net.danlew:android.joda:2.10.9.1'`

should fix this without requiring apps to add joda to their dependencies.

**Comment by moopat** [comment]
I created a pull request for that. :-)

**Comment by ticofab** [comment]
Fixed in 2.0.1
