### ISSUE TITLE
How to get the speed from track points?

### ISSUE THREAD

**Issue by binu8051** [ticofab/android-gpx-parser#39]
Hi, i am trying to use your library and i need the speed of the trackpoint from your sample gpx file
`<ns2:extensions>
<speed>1.4887607411448586791635761983343400061130523681640625</speed>
</ns2:extensions>`

**Comment by ticofab** [comment]
Hey there, the `<speed>` tag is an extension, meaning that it isn't part of the GPX specification and therefore not supported by this parser. Feel free to open a PR to include the speed parameter and it might get merged :)
