### ISSUE TITLE
Access to gpx extensions

### ISSUE THREAD

**Issue by andreasflosdorf** [ticofab/android-gpx-parser#40]
The parser implements the standard Topografix GPX 1.1, in which the attribute 'speed' is not defined, unlike in 1.0. Nevertheless, it is possible as an optional extension. There is also a test case, that includes this attribute, see:
https://github.com/ticofab/android-gpx-parser/blob/master/app/src/main/assets/test.gpx

In the API (io.ticofab.androidgpxparser.parser.domain.TrackPoint) there is no way to access extensions to get the attribute 'speed' if it is present in the gpx file. Speed can be calculated by using existing data (distance and time differences), but if this information is availlavle in the gpx file, there are reasons to use this information. An extension to the API that allows access to GPX Extensions would be great.

**Comment by ticofab** [comment]
Added in 2.2.0
