### ISSUE TITLE
New Way to add jitpack Repo

### ISSUE THREAD

**Issue by ASDFGamer** [ticofab/android-gpx-parser#42]
With the new Gradle Version from Android Studio Arctic Fox (September 2021) it is no longer possible to add repositories via the the allProjects Tag in the root Gradle File. This issue on Stackoverflow shows how it can be done now: [In Android Studio Arctic Fox Canary 8, the app level build.gradle does not generate `allprojects` section and causes error when manually added](https://stackoverflow.com/questions/66475730/in-android-studio-arctic-fox-canary-8-the-app-level-build-gradle-does-not-gener)

I would suggest that the readme is updated to show the new way (and the old way).

**Comment by ticofab** [comment]
Added in README. Thanks!
