### ISSUE TITLE
In the lasted version (2.0.1) I can''t parse from URL, is this not supported anymore?

### ISSUE THREAD

**Issue by marwan-aziz** [ticofab/android-gpx-parser#44]
Using version 2.0.1 - Can't find a way to parse GPX file from URL.

**Comment by ticofab** [comment]
hey @marwan-aziz , that's correct - the URL parsing method has been removed. The reason is that the current implementation was using a bunch of deprecated methods. It should be relatively straightforward to implement it yourself :)

**Comment by ticofab** [comment]
If it can help, here you can see the way it used to be done (now deprecated):
https://github.com/ticofab/android-gpx-parser/commit/61ce8bb788de32d410fd2a8b216f7a01758ab798

I would recommend to implement async parsing using the latest and recommended technique.
