### ISSUE TITLE
Write to file

### ISSUE THREAD

**Issue by paulsUsername** [ticofab/android-gpx-parser#46]
I have built out a GPX file using the Builder methods. I am also parsing separately. How do I write the resultant Gpx object to a file?

**Comment by ticofab** [comment]
Hey @paulsUsername, 
Writing to a file is not in the scope of this library, but maybe this FileWriter from the Androi documentation can help:
https://developer.android.com/reference/java/io/FileWriter
If you want to build a serializer for a parsed GPX object, feel free to open a PR :)
Cheers
Fabio
