### ISSUE TITLE
Improve Library Release Structure

### ISSUE THREAD

**Issue by StuStirling** [ticofab/android-gpx-parser#5]
At the moment there is a lot of code within the library module's `build.gradle` file that I assume is related to the library's release.

Is there a way to remove a lot of this? I haven't done many library releases but the one I have done hasn't need any of this code. There is one module in particular that causes an issue and thats `classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'`. I believe this is because you need to apply the plugin in the module that depends on it which isn't ideal. I am not sure what this is for so can't definitely remove it.

**Comment by ticofab** [comment]
Hey Stu, what issues are caused by the android-maven-gradle-plugin?

**Comment by StuStirling** [comment]
I get the error 

`Error:Plugin with id 'com.github.dcendents.android-maven' not found.`

**Comment by StuStirling** [comment]
Feel free to close this. It was more because I was trying to develop the library module in my own application so problems were caused.
