### ISSUE TITLE
Publishing to Maven central

### ISSUE THREAD

**Issue by jsoberg** [ticofab/android-gpx-parser#51]
Would there be any interest in publishing this library to Maven central instead of requiring Jitpack? I'd love to be able to remove the Jitpack dependency if possible, and would be happy to help in adding this support 👍

**Comment by ticofab** [comment]
hey @jsoberg , thanks for opening this issue. I understand that moving to Maven would remove one step / dependency in the build file. From my perspective, Jitpack does the job and I have an established flow to work with it. I am very grateful for your offer to support the migration but I'll respectfully decline for the time being :) Shall this idea pop up more frequently going forward I'll definitely consider it!
