### ISSUE TITLE
Complete the Waypoint Type parsing

### ISSUE THREAD

**Issue by ticofab** [ticofab/android-gpx-parser#6]
At the moment, this library only parses a few information from a waypoint block, namely

- latitude
- longitude
- elevation
- time

We need to complete the parsing of the waypoint type with all the information described here: http://www.topografix.com/GPX/1/1/#type_wptType

which include, among others,

- waypoint classification
- waypoint name
- waypoint description
- ....

**Comment by mopfattn** [comment]
Waypoints and waypoint names are parsed in https://github.com/ticofab/android-gpx-parser/pull/8

**Comment by ticofab** [comment]
Version 0.2.0 has been released! :)

**Comment by monossido** [comment]
The library still not parse the "desc" (description) field, am I wrong?

**Comment by StuStirling** [comment]
I believe it does as I added this a while back. Could you shares me of the GPX you're parsing?

**Comment by monossido** [comment]
Here https://github.com/ticofab/android-gpx-parser/blob/master/parser/src/main/java/io/ticofab/androidgpxparser/parser/domain/Point.java there isn't  the "description" filed

**Comment by StuStirling** [comment]
According the specs listed here http://www.topografix.com/GPX/1/1/#type_ptType there isn't a `desc` field on this data point.

**Comment by monossido** [comment]
is "wptType" the right component to watch?
http://www.topografix.com/GPX/1/1/#type_wptType

**Comment by frogboiled** [comment]
The library (1.1.2) still not parse the <desc> (description) field from waypoint!
Can you please add it in the next version?
thanks in advance.

// part from real gpx file.
<wpt lat="48.859730" lon=" 2.351660">
    <time>2015-09-14T06:54:35Z</time>
    <name>-=1=-</name>
    <ele>150</ele>
   <desc>A text description of the element. Holds additional information about the element intended for the user, not the GPS.</desc>
</wpt>
