### ISSUE TITLE
Add Testing

### ISSUE THREAD

**Issue by StuStirling** [ticofab/android-gpx-parser#7]
At the moment there is no testing. I suggest getting some unit tests written. 

What would be the suggested pattern for this? We could have a test GPX file that we read in from the assets in the parser module, run it through the `parser` and check the track result at the end?

The only issue with this is it's not very small and not really a unit test more of an end-to-end test? Would this be ok if we had separate tests for each thing?

**Comment by mopfattn** [comment]
I added a test in my pull request (https://github.com/ticofab/android-gpx-parser/pull/8). 

It runs as an androidTest, because the parser requires a working joda-time-android that has to be initialized with a valid Context.
